### ISSUE TITLE
Localization not working as expected

### ISSUE THREAD

**Issue by NKnuelle** [jan-vince/smallgdpr#10]
Hi @jan-vince 
first of all - Thank you for this awesome plugin!

I am currently facing a bug with localization:
My backend user's language setting is set to german. The layouts default language is 'de', too. The problem is, that the buttons for saving the cookie settings still have the english strings:
<img width="630" alt="Cookie_Bug" src="https://user-images.githubusercontent.com/24235417/107153903-46cc9b80-6970-11eb-8b93-fbb3b8a267ff.PNG">

There is no setting in the backend to change this button texts and as I see in the code, the button text should be translated - but this is not working properly.

Do you know what the problem is here?

Thanks in advance!

**Comment by evwerkz** [comment]
Hi, I will check that.

**Comment by evwerkz** [comment]
> Hi @jan-vince
> first of all - Thank you for this awesome plugin!

benutzt du das Translate Plugin?

**Comment by NKnuelle** [comment]
Oh, Nein. Bisher nicht. Welches denn?

**Comment by jan-vince** [comment]
Hi @NKnuelle, for start check if you have the latest plugin's version as translated strings are read from `/lang/de/lang.php` file.

Translate plugin is not necessary but without it you need to have the correct language set in `/config/app.php`.

I'm using DE locale (without Translate plugin) on https://www.alvao.com/de.

**Comment by NKnuelle** [comment]
Hi @jan-vince - The plugin was installed today and is up-to-date. I also installed the translate plugin but that was not enough. After setting the locale in the `/config/app.php` the cookie message is translated correctly to german. Thank you!

**Comment by evwerkz** [comment]
oh ok, you mean 'locale' => 'de', and 'fallback_locale' => 'en', configs.

**Comment by jan-vince** [comment]
@NKnuelle ok :) 

I will add to my todo to allow custom text for both buttons.
 
---

@evwerkz Translate plugin will also change locale (when you set it in Settings), but is not necessary for single language sites.

Thank you for offering help to @NKnuelle, appreciate it :)
