### ISSUE TITLE
Argument $name must be of type string

### ISSUE THREAD

**Issue by LZaplata** [jan-vince/smallgdpr#12]
Hi,
I tried to implement your plugin, but it gives me an error. Is it possible to solve it? Thanks.

Cms\Classes\ComponentBase::addCss(): Argument #1 ($name) must be of type string, array given, called in /home/zap/public_html80/october/plugins/janvince/smallgdpr/components/CookiesBar.php on line 50

**Comment by evwerkz** [comment]
Hi, i have a same problem with October V.2.

My solution is:

use System\Classes\CombineAssets;

switch( CookiesSettings::get('cookies_bar_add_styles', null)) 
            {
                case 2:
                    $css = ['assets/cookiesbar/cookiesbar-topline.css'];
                    $css = CombineAssets::combine($css, plugins_path('janvince/smallgdpr'));
                    $this->addCss($css);
                    break;
                default:
                    $css = ['assets/cookiesbar/cookiesbar.css'];
                    $css = CombineAssets::combine($css, plugins_path('janvince/smallgdpr'));
                    $this->addCss($css);
                    break;
            }

**Comment by jan-vince** [comment]
Hi @LZaplata and @evwerkz 

what is your October2 exact version? 

I have fresh October2 installation and Small GDPR works without any changes.

[As of documentation](https://octobercms.com/docs/cms/pages#injecting-assets) the original plugin's code should work - `addCss` method accept string or array.

**Comment by LZaplata** [comment]
I can confirm plugin works fine on latest 2.0.14 build. I had the problem with 2.0.12. Still there is tiny display issue with cookies settings modal window. If I set a cookie bar to strip, modal window is little bit scattered. It is not a problem for me, just let you know.

**Comment by evwerkz** [comment]
I've updated October now and the problem is gone too.

**Comment by jan-vince** [comment]
@LZaplata can you post screenshot here? 

I still do not use OC2, but maybe can fix this.

**Comment by LZaplata** [comment]
![image](https://user-images.githubusercontent.com/12596881/119112343-438f8400-ba24-11eb-9717-6101444791e6.png)

**Comment by jan-vince** [comment]
@LZaplata And your Bootstrap version?

*PS: In plugin settings there is an option to set UI style to Bootstrap 3 or Bootstrap 5.*

**Comment by LZaplata** [comment]
Yes I know, I have Bootstrap 5 and I set it. Modal is fine with cookies bar box style, display issue is only with stripe (up) style. Other thing is that stripe is fixed down not up.

**Comment by jan-vince** [comment]
Ok, I will look at this when I will start to test OC2 and Bootstrap 5.
