### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by evwerkz** [jan-vince/smallgdpr#13]
Hi, I have the following problem.

I have a project where the page is displayed via iframe.
The cookie banner cannot be confirmed by clicking OK. After page reload, the banner is displayed again and the JS scripts to be followed, e.g. matomo, are not loaded.

Do you have any idea how to solve it?

**Comment by jan-vince** [comment]
HI @evwerkz, I have no experience with using this inside of iFrame.

I guess iFrame prevents of saving cookies, maybe like this: https://medium.com/trabe/cookies-and-iframes-f7cca58b3b9e
