### ISSUE TITLE
"Open Modal Window" not working even with Bootstrap 3 style

### ISSUE THREAD

**Issue by Chinyoka1** [jan-vince/smallgdpr#15]
It only adds #sg-settings-modal-cookiesBar to the url, but no modal window is opened. I double checked that I have the Bootstrap 3 UI style selected in the settings and also tried the other UI styles.

**Comment by jan-vince** [comment]
Hi,

can you create functional modal (by hand) on the same page.

This is usually caused by missing JavaScript, non functional jQuery, ...

*I use Small GDPR on all of my projects with Bootstrap 3 and it works.*
