### ISSUE TITLE
Issues with OctoberCMS v3.0.37

### ISSUE THREAD

**Issue by mediaclinic** [jan-vince/smallgdpr#19]
Got error:

php artisan project:sync In Yaml.php line 43:

A syntax error was detected in /.../octobercms3/plugins/janvince/smallgdpr/updates/version.yaml. The string "!!! Cookies JS code placed in code window now requires <script> tags to be present! Please check your code." could not be parsed as it uses an unsupported built-in tag at line 64 (near "1.4.5: !!! Cookies JS code placed in code window now requires <script> tags to be present! Please check your code.") at line 43 (near "/.../octobercms3/vendor/october/rain/src/Parse/Yaml.php").

**Comment by jan-vince** [comment]
Hi and thanks for issue.

This is fixed in 1.18.1
