### ISSUE TITLE
"Illegal string offset 'show_modal'" 

### ISSUE THREAD

**Issue by aleksejsresko** [jan-vince/smallgdpr#2]
Hi and thank you for the plugin! 
I have an issue, trying to translate cookie bar buttons, by creating the buttons for each language, the plugin shows an error and doesn't allow to switch between languages.
""Illegal string offset 'show_modal'" on line 546 of /home/site/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php"

**Comment by jan-vince** [comment]
Hi @aleksejsresko and thanks for issue.

This is fixed in version 1.5.1.


Best regards,

Jan
