### ISSUE TITLE
Is it possbile to make a manual update of plugin?

### ISSUE THREAD

**Issue by 01Kuzma** [jan-vince/smallgdpr#20]
Hi!
Thank you for the great plugin!
I've been using the outdated version `1.8.1` installed on `October CMS`. Now it's not possible to update it through the admin panel.
I've downloaded the latest version from `GIT` and copied all the files to my website. 
In the backend it's still the `1.8.1` version. 
Is it possible to run a `SQL` script in DB or make something to update it? 
My website runs on shared hosting, so there is no possibility to run any commands.

Thanks!

**Comment by jan-vince** [comment]
What version of October do you use?

If 1.0 (or 476) try to install any of marketplace plugins - this will trigger migrations.

**Comment by 01Kuzma** [comment]
It's 1.0, 471 :(
It's not updating to 476 or newer

**Comment by jan-vince** [comment]
Try to upload Small GDPR files and try to install any other plugin from backend if this force Small GDPR to update.

But you should upgrade do (min) 476 anyway.

**Comment by 01Kuzma** [comment]
Thank you!
This did the trick!
As I understand, without the licence it's not possible to upgrade October CMS from `471` to `476`?

**Comment by jan-vince** [comment]
476 is still free

**Comment by 01Kuzma** [comment]
Thanks!
Googling gives me information, that the update is only possible through a `Composer`, not from backend :(
