### ISSUE TITLE
Google Tag Manager compatibility?

### ISSUE THREAD

**Issue by 01Kuzma** [jan-vince/smallgdpr#21]
Hello!
I'm having an additional question regarding cookie consent management.
On the website, I use **Google Tag Manager**, the code script must be placed at the beginning of the  `<head> ` and `<body> ` sections.
In the plugin settings section, there is `Custom JS code` window, and `GTM` code placed there won't be rendered at the beginning of the  `<head> ` and `<body> ` sections accordingly.
So, is there a solution to make it work in the right way? Or could it be as a feature request?

For a more convenient way, I use this [plugin](https://github.com/alekseyp/octobercms-googletagmanager)
Or maybe there is a solution to execute this plugin with a given user consent with your plugin?

Thank you!

**Comment by jan-vince** [comment]
I have got a blog post about GTM integration: https://www.webula.cz/blog/small-gdpr

In czech, but you can use translator. 


Jan



Ing. Jan Vince / webdesigner / +420 733 127 581 / www.vince.cz

**Comment by 01Kuzma** [comment]
@jan-vince ,
thank you! That helped!
But there is a small bug: if I accept all cookies (in my example I've grouped the `ads` and `stats` into one category) , then go to `/gdpr` page, untick the appropriate category with `ads and stats` - cookies are not deleted.
![image](https://user-images.githubusercontent.com/569504/184476917-9059f09a-d4d7-43d2-8665-64d99ea62f55.png)

**Comment by jan-vince** [comment]
Do you have cookiesManage component present on your /gdpr page?

I use Small GDPR on many sites and deleting cookies works.

**Comment by 01Kuzma** [comment]
Yes, I do
![image](https://user-images.githubusercontent.com/569504/184493421-4e24e5a1-ce0b-4287-9e23-42d920cd5492.png)

**Comment by jan-vince** [comment]
I have tested right now and works for me. 

Try to delete all cookies and test again.

**Comment by 01Kuzma** [comment]
hm, that's strange, My cookies are not erased after once I untick the category. 
For a test, I clear them through a WebDeveloper Tools
Could you take a look? Here is a [gdpr page](https://filmustudija.lt/gdpr) and [here the homepage](https://filmustudija.lt/)
Maybe I'm doing something wrong...

**Comment by jan-vince** [comment]
Works for me.

I have clicked Accept all and then on /gdpr page a have unclicked "Statistical, ...". After "Save settings" cookie is removed.

I am using Safari.
<img width="1078" alt="Snímek obrazovky 2022-08-13 v 14 48 42" src="https://user-images.githubusercontent.com/1104383/184494800-bbc1553f-6b0d-439d-ac10-3a70f42d5839.png">

<img width="1078" alt="Snímek obrazovky 2022-08-13 v 14 48 47" src="https://user-images.githubusercontent.com/1104383/184494812-fd8cf901-3c9f-48d1-a5e4-fb7fdb940f62.png">

<img width="1078" alt="Snímek obrazovky 2022-08-13 v 14 49 01" src="https://user-images.githubusercontent.com/1104383/184494816-724e5167-bffc-4a7b-a594-e28f2425d2c2.png">

**Comment by 01Kuzma** [comment]
Thank you that you have checked it!
That's strange, I'm using Firefox and Chrome in private mode, but once I unclick the second cookies category they still remain...
That's very strange...
Here is a screenshot after I have unclicked the statical and marketing cookies:
![image](https://user-images.githubusercontent.com/569504/184495545-b8697305-54fe-4dd1-9623-425c305b8450.png)

**Comment by jan-vince** [comment]
Have you tried to refresh the page?




< Ing. Jan Vince / webdesigner / +420 733 127 581 / www.vince.cz />

**Comment by 01Kuzma** [comment]
Yes, pressing Ctrl+R/F5, and working in private mode...

**Comment by jan-vince** [comment]
I will test it in Chrome and let you know



Ing. Jan Vince / webdesigner / +420 733 127 581 / www.vince.cz

**Comment by 01Kuzma** [comment]
Thank you!

**Comment by 01Kuzma** [comment]
Hi!
Any news?

**Comment by 01Kuzma** [comment]
Hello,
thank you for your reply!
That's strange, I still experience that strange behaviour. I'll try to update the CMS to the latest version, maybe it has some influence...
Just my two cents regarding the feature request, if it will be possible in the future: it would be great if the banner could be revokable after the consent is given. And exploring the GDPR requirements, they suggest temporary log the given/not given user consent

**Comment by jan-vince** [comment]
I will add this to my todo list :)

Best regards,

Jan
