### ISSUE TITLE
Button not run JS script after Accept-all Button click

### ISSUE THREAD

**Issue by afdstudio** [jan-vince/smallgdpr#26]
Hi. I am using OctoberCMS V3.3.20 with SmallGDPR V1.23.00 but even the Accept-all and the Disable-all button doesn't work. Not sure where is the issue here.
Is it possible to check here?
https://www.thevalleyresidence.com/coming-soon

In October V2 never got an error and I am trying now the V3. I am newbie on this version.

Thank you in advance!

**Comment by jan-vince** [comment]
You have some JS error on your site - I would start with that.

And be sure, you have {% scripts %} tag in your layout file.

**Comment by afdstudio** [comment]
HI @jan-vince ! Thanx for the reply! Indeed there's some conflict with my scripts.
