### ISSUE TITLE
Unable to export settings

### ISSUE THREAD

**Issue by Pixinside** [jan-vince/smallgdpr#29]
I got this error: 
[Error] Error: Error parsing the data-request-data attribute value. Error: Broken JSON body near ath: /storage/app/media/small-gdpr-export.yaml}
	f (framework-bundle.min.js:1:6093)
	r (framework-bundle.min.js:1:10053)

with October 3.5.7

**Comment by jan-vince** [comment]
@Pixinside Thanks - fixed in v1.23.1.
