### ISSUE TITLE
Problem with adding GA code 

### ISSUE THREAD

**Issue by pearpl** [jan-vince/smallgdpr#30]
Im tryin to use **Small GDPR** plugin October 3.5.12, it seems to work but it doesn't add the GA code when i agree to cookies also when i try to save custom settnings `Error: Incorrect contents fetched, please reload.`

**Comment by jan-vince** [comment]
Have you tried to import default preset? You can use it as a reference.

In Settings > Cookies > tab Import > btn Import default settings.

I use this plugin on many sites without any problem.

**Comment by pearpl** [comment]
that's exactly what i did for initial data.

**Comment by jan-vince** [comment]
Where do you call plugin's component? in layout or CMS page?

**Comment by pearpl** [comment]
Yes in layout

**Comment by jan-vince** [comment]
Sorry, I have no time to make consultations for free plugins. 

I can look here time to time and try to help, but i have created this plugin primarily for my own use and it works for me.
