### ISSUE TITLE
Bootstrap 5 data-attribute is different from Bootstrap 3

### ISSUE THREAD

**Issue by impactfactory** [jan-vince/smallgdpr#7]
They area all now data-bs-function. I hope I fixed it correctly for your lovely and helpful Plugin, please have a look  :)

[smallgdpr.zip](https://github.com/jan-vince/smallgdpr/files/5755260/smallgdpr.zip)

https://getbootstrap.com/docs/5.0/components/modal/

**Comment by evwerkz** [comment]
Thx, i add pull request to fix it

**Comment by jan-vince** [comment]
Hi @evwerkz and @impactfactory and thank you both. This is implemented in version 1.8.1.

Best regards,

Jan
