### ISSUE TITLE
Redirect to the main page

### ISSUE THREAD

**Issue by sagjatome** [jan-vince/smallgdpr#9]
After clicking on the agreement button, a redirect to the main page takes place, is it possible to add a setting so that the user remains where he is?

**Comment by evwerkz** [comment]
Hi,

did you habe some errors? I use this plugin in many projects and have made a small contribution to the plugin, but I am not aware of this problem. I just tested if after "accept" or after "save settings" it redirects to the home page. I stayed on a subpage and was not redirected, I even stayed in the position I scrolled to.

Check the PHP logs to see if there are any errors. What version of PHP are you using? 
Have you updated the plugin yet?

**Comment by sagjatome** [comment]
Hi, I don't have any errors, use PHP 7.3 with apache module, have the latest version. Thank u for attention.

> did you habe some errors? I use this plugin in many projects and have made a small contribution to the plugin, but I am not aware of this problem. I just tested if after "accept" or after "save settings" it redirects to the home page. I stayed on a subpage and was not redirected, I even stayed in the position I scrolled to.
> 
> Check the PHP logs to see if there are any errors. What version of PHP are you using?
> Have you updated the plugin yet?

**Comment by jan-vince** [comment]
Hi @sagjatome,

there is an option to set redirect URL for each of those buttons in Cookies bar (in backend Settings > Cookies; tab Cookies bar). 

What URL do you have there?

**Comment by sagjatome** [comment]
> What URL do you have there?
I had "/" there but now it is empty but I still have to go to homepage...

**Comment by sagjatome** [comment]
I have created all buttons from beginning again but it doesn't work - I get the main page.

**Comment by jan-vince** [comment]
Hi @sagjatome, 

I use hash (#) to stay on the current page. This is very badly documented - I will fix it!

*And now I see there is not very good URL handling in my code - I would like to add AJAX and better redirect/reload method to this. I have to find some time to fix this.*

Let me know it hash in URL will fix your problem.

**Comment by sagjatome** [comment]
> Let me know it hash in URL will fix your problem.

Yes, it helps, thanks a lot,@jan-vince

**Comment by sagjatome** [comment]
> Hi @sagjatome,
> 
> I use hash (#) to stay on the current page. This is very badly documented - I will fix it!
> 
> _And now I see there is not very good URL handling in my code - I would like to add AJAX and better redirect/reload method to this. I have to find some time to fix this._
> 
> Let me know it hash in URL will fix your problem.
Now I have the same problem.
can you find a time and fix what you said with add "AJAX and better redirect/reload method". How it is possible?

**Comment by jan-vince** [comment]
Hi @sagjatome, I will try to find some time this weekend.

**Comment by jan-vince** [comment]
hi @sagjatome,

I have added version 1.12.1 that should fix some of the problems:

* I have fixed handling of buttons URLs
* I have added option to disable page reload after cookies are set

**Comment by sagjatome** [comment]
Hi, @jan-vince, that is nice from you. Thanks a lot!
Best regards,
Y.Melnyk
